# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class SurgeConfirmation < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :href

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :surge_confirmation_id

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["href"] = "href"
        @_hash["surge_confirmation_id"] = "surge_confirmation_id"
      end
      @_hash
    end

    def initialize(href = nil,
                   surge_confirmation_id = nil)
      @href = href
      @surge_confirmation_id = surge_confirmation_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      href = hash['href']
      surge_confirmation_id = hash['surge_confirmation_id']

      # Create object from extracted values
      SurgeConfirmation.new(href,
                            surge_confirmation_id)
    end
  end
end
