# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class Vehicle < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :license_plate

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :make

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :model

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["license_plate"] = "license_plate"
        @_hash["make"] = "make"
        @_hash["model"] = "model"
      end
      @_hash
    end

    def initialize(license_plate = nil,
                   make = nil,
                   model = nil)
      @license_plate = license_plate
      @make = make
      @model = model
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      license_plate = hash['license_plate']
      make = hash['make']
      model = hash['model']

      # Create object from extracted values
      Vehicle.new(license_plate,
                  make,
                  model)
    end
  end
end
